spring.application.name=repo0410

server.port=80

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521/xe
spring.datasource.username=C##KH
spring.datasource.password=1234

#JPA
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#spring.jpa.hibernate.ddl-auto=update

# spring.jpa.hibernate.ddl-auto=create

# spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.hibernate.ddl-auto=validate